var apiUrl = {
  user: "/users",
  userLogin: "/users/login",
  userSearch: "/users/search",
  userChange: "/users/chang",
  userAdd: "/users/register",
  userDelete: "/users/delete",
  tag: "/tag",
  tagList: "/tag/all",
  tagSearch: "/tag/search",
  tagUpdate: "/tag/update",
  tagDelete: "/tag/delete",
  tagAdd: "/tag/add",
  addSystem: "/system/add",
  updateSystem: "/system/update",
  getSystem: "/system",
  uploadImg: "/upload/add",
  articleAdd: "/article/add",
  articleList: "/article",
  articleUpdate: "/article/update",
  articleDelete: "/article/delete",
  articleSearch: "/article/search",
  sayGet: "/say",
  saySearch: "/say/search",
  sayAdd: "/say/add",
  sayUpdate: "/say/update",
  sayDelete: "/say/delete",
  gutsbppkGet: "/gustbook",
  gutsbppkDelete: "/gustbook/delete",
  gustbookState: "/gustbook/state",
  gustbookReply: "/gustbook/reply",
  imageGet: "/images",
  imgDelete: "/images/delete",
  bannerAdd: "/banner/add",
  bannerGet: "/banner",
  bannerUpdate: "/banner/update",
  bannerDelete: "/banner/delete",
  bannerFind: "/banner/find",
  bannerState: "/banner/state",
  total: "/total",
  totalTags: "/total/tags",
  verifySecret: "/users/verifySecret"
};

export { apiUrl };
